
WindowManager:
    MainWindow:
    NotificationWindow:
    MenuWindow:

<MainWindow>:
    name: "main"



    GridLayout:
        cols: 2
        height: "50dp"
        size_hint_y: None
        Button:
            text: "Notifications"
            on_release: app.root.current = "second"

        Button:
            text: "Menu"

<NotificationWindow>:
    name: "second"

<MenuWindow>:
    name: "third"

    Label:
        text: "You Made it!!"
